### ISSUE TITLE
[BUG] '/cases/confirmed' endpoint response is limited

### ISSUE THREAD

**Issue by Steven-MKN** [dsfsi/covid19za#120]
**Describe the bug**
When making a get request to the **/cases/confirmed** endpoint the data is limited only until the 25th of march 2020.

**To Reproduce**
1. Go to https://covid-za-api.herokuapp.com/cases/confirmed either with a script or browser.
2. Notice the data is represents data only until the 25th of march 2020

**Expected behavior**
I expect to be able to get the data dated up until the date of the last update as presented on the dashboard

I believe this can be solved by enabling the API to stream the response since it is a large amount of data it is sending

**Comment by Vutlhari** [comment]
The API pulls the data from the CSV files. With that said;

Since around 24 March, we have not gotten individual case data from DoH or NICD. For now if you need provincial counts use the provincial_cumulative_timeline. For indivividual cases up to 25 March, use the confirmed_cases.

There is an issue opened to expose the provincial_cumulative_timeline.

**Comment by Steven-MKN** [comment]
Thanks Bro. Just one more thing. Along with "/cases/timeline/tests" can we get a it to show cumulative positive cases?

**Comment by Vutlhari** [comment]
> Thanks Bro. Just one more thing. Along with "/cases/timeline/tests" can we get a it to show cumulative positive cases?

I will have to check if that data is available in any of the csv files

**Comment by vukosim** [comment]
@Vutlhari the final column in the province data is the total
