### ISSUE TITLE
[Feature] Updates are not often enough to match the irregular announcements.

### ISSUE THREAD

**Issue by Garfsfield** [dsfsi/covid19za#194]
A cron job which runs every 5 to 15 minutes would ensure that updates are mined from the NICD released files a lot better.

i.e */12 * * * * (run covid update file) >/dev/null 2>&1

**Comment by vukosim** [comment]
@Garfsfield NICD no longe releases their statements in timely points. So volunteers work to read the statements that the minister or premiers publish (which are not yet standardisedO

**Comment by lostpebble** [comment]
@vukosim thank you so much for the work you and the other volunteers are doing. I know its not easy to keep everything up to date all the time because the information is released sporadically and sometimes only in images on Twitter etc.

I would like to help contribute as well, as I'm sure many others would too.

Could we not maybe start a discord or slack server, basically a place for everyone who has an interest in South African / African Covid 19 data to congregate and notify each other when data changes happen so people can more easily be aware and contribute? Might help to keep things better updated when communication is more streamlined.

Thanks again for putting this together and all the efforts you've done to maintain and grow it!

**Comment by vukosim** [comment]
We do have a discord https://discord.gg/BgP8HHj

**Comment by vukosim** [comment]
@Garfsfield if you can assist with  automation scripts for some of the tasks that you think can be automated, please do.

**Comment by bmerry** [comment]
Out of interest, is there any collaboration with other groups making dashboards e.g. [Wits/iThemba/Dataconvergence](https://www.covid19sa.org/) or [Mediahack](https://mediahack.co.za/datastories/coronavirus/dashboard/)? While the different displays contribute different insights, I'm sure there would be value in sharing the work on data capture.

**Comment by vukosim** [comment]
@bmerry we will stay committed on working publicly [the dashboard on our end is not the main work but the repo itself].
