### ISSUE TITLE
[DATA] GP District Datasets - column heading changes and key mismatch

### ISSUE THREAD

**Issue by Strasheim88** [dsfsi/covid19za#370]
## Which Dataset
covid19za/data/district_data/gp_ekurhuleni.csv
covid19za/data/district_data/gp_johannesburg.csv
covid19za/data/district_data/gp_sedibeng.csv
covid19za/data/district_data/gp_tshwane.csv
covid19za/data/district_data/gp_westrand.csv

## Error Description
Column headings were changed and now do not match with keys on district_gp_keys.csv

## Suggested fixes
  1. Change column headings to coincide with keys.
  2. Do not change column headings again - messes with data pipelines.

**Comment by shaze** [comment]
Sorry being changed as result of another thread. I'll try to fix when I push today's data

**Comment by shaze** [comment]
Can we discuss this -- the district names do match (at least most do I could have missed one) but there is multiple data here.

So for example we have "Johannesburg A Cases" and "Johannesburg A Recoveries"
(There is a space between Johannesburg and A and a tab between A and Recoveries) and similarly with the others).

I am bringing @heerden in on this too since I broken some of his scripts too and I'd like agreement.

As an aside: I have one big file  that contains all the data and a script that generates the provincial and metro data so I can make changes fairly easily but I'd like consensus so we can sort this out and stop breaking scripts.

**Comment by heerden** [comment]
We agreed to update the `GP Total` header in the previous thread. I am not going into a discussion on the spaces between titles again. It is fine with me if we design freeze now.

**Comment by shaze** [comment]
I have pushed the figures from yesterday through. I've been through the labels to try to ensure consistency. Please let me know of any outsanding issues.

**Comment by Strasheim88** [comment]
I see. I will adapt my script to take space vs tab logic into account.
