### ISSUE TITLE
[DATA] NW NC swap

### ISSUE THREAD

**Issue by 18306063** [dsfsi/covid19za#448]
## Which Dataset
provincial_cumulative_timeline_recoveries

## Error Description
The values for Northern Cape and Northwest recoveries are swopped around and don't correspond to the NICD stats.

## Suggested fixes
  1.
  1.
  1.

**Comment by shaze** [comment]
Underlying problem I think is that the abbreviations NC and NW are in reverse lexicographic order to Northern Cape and North West Province.

**Comment by vukosim** [comment]
Thanks for this. Will work on to resolve. @18306063

**Comment by chadwpetersen** [comment]
This a good clean up -however, making this change could potentially break downstream services that are naively using column order instead of csv headers. I doubt it would be a major issue but just noting the associated risk with this change :). 

Making this change will also make capturing the data a bit easier as well as decrease the risk of capturing wrong data as this has happened before a few times. Also note this would also apply to the provincial cumulative confirmed and deaths csv files as well. :)

Are there any other known files that would require this swop? We might as well do it to all of them.

**Comment by chadwpetersen** [comment]
I could build a quick go/python tool that can swop two columns in a csv file -just incase we might want to do this again at some point? That way we eliminate any data issues we could introduce during the data swopping process and swopping back in case of an issue would be simple as well.

**Comment by vukosim** [comment]
Think we can and will fix anything on our dashboard that might use it @chadwpetersen
