### ISSUE TITLE
[Feature] Validate current csv list with DoH PDF

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#55]
See the pdf here. https://sacoronavirus.co.za/wp-content/uploads/2020/03/Latest-confirmed-cases-21-March-.pdf.pdf.pdf

DoH has now created a sheet inside the PDF that has some patient demographics. Can we validate these with our confirmed list.

**Comment by vukosim** [comment]
[Latest-confirmed-cases-21-March-.pdf.pdf.pdf](https://github.com/dsfsi/covid19za/files/4362827/Latest-confirmed-cases-21-March-.pdf.pdf.pdf)

**Comment by elolelo** [comment]
@vukosim So ,  I took quick look at the files to compare the lists and  try to validate - here are some  differences that are easy to spot 

1. Gender counts = The gov doc has 96 female whereas our confirmed list has 88 females and 5 not specified

2.Provinces  = KZN in the gov doc has 27 confirmed cases but we have 26 confirmed cases and the WC has 74 in the gov doc while we have its cases as 75
Other than these 2 provinces - others seem to be ok.

3. Age = In the gov doc - case #. 4's age is 37  not 38 as we have it. There is no 51 years old male in KZN from the government doc

There seems to be a lot of minor differences in terms of age and places - what is the best way to outline these differences instead of commenting them out?

**Comment by vukosim** [comment]
I will take a look tonight. We need a few people to validate so might slow down for the next 24 to 48 hours so that we can validate. We are unfortunately not getting data from NICD statements anymore.
