### ISSUE TITLE
[DATA] Incorrect value in date column for provincial_gp_cumulative.csv and gp_*.csv 

### ISSUE THREAD

**Issue by SimonRosen173** [dsfsi/covid19za#580]
## Which Dataset
 - provincial_gp_cumulative.csv
 - gp_*.csv's

## Error Description
Last field in date column is incorrect. It is 18-07-2-2- on 18-07-2020.

## Suggested fixes
  1. Change field to 18-07-2020.

**Comment by theauheral** [comment]
Same issue here :)

**Comment by shaze** [comment]
I've pushed through today's figures with the corrections. Apologies for any inconvenience. Let me know if there are any other open issues.

**Comment by theauheral** [comment]
Thank you very much!! :)Théau Héral    On Mon, Jul 20, 2020 at 5:34 PM Scott Hazelhurst <notifications@github.com> wrote:I've pushed through today's figures with the corrections. Apologies for any inconvenience. Let me know if there are any other open issues.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by shaze** [comment]
Thanks -- am closing
